server:
  port: 8082

spring:
  application:
    name: booking-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lineleap_booking

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka