server:
  port: 8083

spring:
  application:
    name: customer-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lineleap_customer

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka